<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="HelloWorldService"
     targetNamespace="http://oracle.com/sca/soapservice/HeloWorld/HelloWorldProject/HelloWorldService"
     xmlns:tns="http://oracle.com/sca/soapservice/HeloWorld/HelloWorldProject/HelloWorldService"
     xmlns:inp1="http://xmlns.oracle.com/singleString"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.oracle.com/singleString" schemaLocation="../Schemas/singleString.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="Entrada" element="inp1:singleString"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="Respuesta" element="inp1:singleString"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
